heat_template_version: 2018-08-31

description: Template to deploy all virtual machines of the final scenario

resources:
#
# Firewall, rules and policies
#
  fw:
    type: OS::Neutron::Firewall
    properties:
      description: Firewall para filtrar el trafico exterior
      firewall_policy_id: {get_resource: fw_policies}
      name: Firewall
      value_specs: {...}
  fw_policies:
    type: OS::Neutron::FirewallPolicy
    properties:
      audited: Boolean
      description: String
      firewall_rules: [Value, Value, ...]
      name: String
      shared: Boolean
  fw_rules:
    type: OS::Neutron::FirewallRule
    properties:
      action: String
      description: String
      destination_ip_address: String
      destination_port: String
      enabled: Boolean
      ip_version: String
      name: String
      protocol: String
      shared: Boolean
      source_ip_address: String
      source_port: String
