heat_template_version: 2018-08-31

description: Template to deploy all virtual machines of the final scenario

#
# Our LBaaS V2 "Load Balancer"
#
resources:
  lb:
    type: OS::Neutron::LBaaS::LoadBalancer
    properties:
      vip_subnet: subnet1