heat_template_version: 2021-01-03

description: Template to deploy all virtual machines of the final scenario

resources:
  s1:
    type: OS::Nova::Server
    properties:
      name: s1
      image: xenial-server-cloudimg-amd64-vnx
      flavor: m1.smaller
      networks:
       - network: net1
       - network: net2
      user_data:
  s2:
    type: OS::Nova::Server
    properties:
      name: s2
      image: xenial-server-cloudimg-amd64-vnx
      flavor: m1.smaller
      networks:
       - network: net1
       - network: net2
  s3:
    type: OS::Nova::Server
    properties:
      name: s3
      image: xenial-server-cloudimg-amd64-vnx
      flavor: m1.smaller
      networks:
       - network: net1
       - network: net2
  admin:
    type: OS::Nova::Server
    properties:
      name: admin
      image: xenial-server-cloudimg-amd64-vnx
      flavor: m1.smaller
      networks:
       - network: net1
       - network: net2
  lb:
    type: OS::Nova::Server
    properties:
      name: lb
      image: xenial-server-cloudimg-amd64-vnx
      flavor: m1.smaller
      networks:
       - network: net1
       - network: net2
  bbdd:
    type: OS::Nova::Server
    properties:
      name: bbdd
      image: xenial-server-cloudimg-amd64-vnx
      flavor: m1.smaller
      user_data_format: RAW
      user_data: |
        #cloud-config
        # Update apt database on first boot
        apt_update: true
        # Upgrade the instance on first boot
        apt_upgrade: true
        # Add 10gen MongoDB repo
        apt_sources:
         - source: "deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen"
           keyid: 7F0CEB10
           filename: 10gen.list
        # Install packages
        packages:
         - mongodb-10gen
         - ntp
        runcmd:
         - [ sed, -i, "s/# replSet = setname/replSet = twitterdata/g", /etc/mongodb.conf ]
         - [ restart, mongodb ]

      networks:
       - network: net2
  files:
    type: OS::Nova::Server
    properties:
      name: files
      image: xenial-server-cloudimg-amd64-vnx
      flavor: m1.smaller
      networks:
       - network: net2
