heat_template_version: 2018-08-31

description: Template to deploy all virtual machines of the final scenario

parameters:

  subnet1:
    type: OS::Neutron::Subnet
    properties:
     name: subnet1
     network: net1
     cidr: 10.1.1.0/24
  subnet2:
    type: OS::Neutron::Subnet
    properties:
     name: subnet2
     network: net2
     cidr: 10.1.2.0/24

resources:
  s1:
    type: OS::Nova::Server
    properties:
      name: s1
      image: xenial-server-cloudimg-amd64-vnx
      flavor: m1.smaller
      networks:
       - network: net1
       - network: net2
      user_data:

  s2:
    type: OS::Nova::Server
    properties:
      name: s2
      image: xenial-server-cloudimg-amd64-vnx
      flavor: m1.smaller
      networks:
       - network: net1
       - network: net2

  s3:
    type: OS::Nova::Server
    properties:
      name: s3
      image: xenial-server-cloudimg-amd64-vnx
      flavor: m1.smaller
      networks:
       - network: net1
       - network: net2

  admin:
    type: OS::Nova::Server
    properties:
      name: admin
      image: xenial-server-cloudimg-amd64-vnx
      flavor: m1.smaller
      networks:
       - network: net1
       - network: net2
  lb:
    type: OS::Neutron::LBaaS::LoadBalancer
    properties:
     name: LB
     vip_subnet: subnet1

  bbdd:
    type: OS::Nova::Server
    properties:
      name: bbdd
      image: xenial-server-cloudimg-amd64-vnx
      flavor: m1.smaller
      user_data_format: RAW
      user_data: |
        #cloud-config
        runcmd:
          - apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 9DA31620334BD75D9DCB49F368818C72E52529D4
          - echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.0.list
          - apt-get update
          - apt-get install -y mongodb-org
          - service mongod start
      networks:
       - network: net2
  files:
    type: OS::Nova::Server
    properties:
      name: files
      image: xenial-server-cloudimg-amd64-vnx
      flavor: m1.smaller
      networks:
       - network: net2
